### ISSUE TITLE
Figure out internationalization (i18n) / localization (l10n)

### ISSUE THREAD

**Issue by callahad** [portier/portier-broker#116]
We don't have a lot of text, but what we do have needs to be able to be localized.

**Comment by onli** [comment]
https://github.com/portier/portier-broker/commit/cd67f14c4e8fc54fe9ca62a621f8edf3b28097fc implements an i18n scheme using gettext (using https://docs.rs/gettext/0.2.0/gettext/).

Some caveats:

 1. I used variable-like ids instead of the english default text as id, because I dislike having the english text in the sourcecode. I think that conflicts with how gettext is sued normally.
 * The auth handler, where the language detection is implemented currently, might be the wrong place.
 * There might be a better system than giving the text as variables to the mustache templates.
 * I was unable to add a config variable to our .toml scheme, I ran into an error there and just could not fix it. So instead this detects the language the browser requests via the Accept-Language header (which actually should be more difficult…). This would still need testing and probably modification if multiple languages are set in that header.
 * Those *.mo files are binary and maybe should not be in the repo, but then we need to setup Heroku to compile them
 * I could not test the email flow till the end, that still needs testing.

Ah, and most importantly: It seems to work fine :) If you think that approach can would be okay for us I'd like to open a PR.

**Comment by callahad** [comment]
This is awesome! I don't have a lot of experience with i18n, so a few questions:

> I used variable-like ids instead of the english default text as id, because I dislike having the english text in the sourcecode. I think that conflicts with how gettext is used normally.

I think you're right that gettext is most commonly used with English literally in the source. I imagine this is useful since any changes to the English would automatically invalidate the translations. Without that, how else would we flag strings that need updates?

> I was unable to add a config variable to our .toml scheme, I ran into an error there and just could not fix it.

Yeah. The logic in the config stuff is good, but the source is really unwieldy. Prime target for a refactor after 1.0. Macros to the rescue? Or deeper Serde voodoo? There's got to be something. Updating https://github.com/softprops/envy to work with Serde 0.8 would let us remove [a few lines](https://github.com/portier/portier-broker/blob/master/src/config.rs#L421-L455).

> Those *.mo files are binary and maybe should not be in the repo, but then we need to setup Heroku to compile them

Would it make sense to compile them on the fly at server startup? What's a normal workflow there? Do folks really stop and manually recompile the .po files after every change?

**Comment by stephank** [comment]
Really cool! Bummer that Mustache kind of breaks down here, and we can't do `{{ _ "Foo" }}` or similar.

Maybe we can have the template helper merge in *all* translations, considering we don't have a lot anyway? Might make things easier, but I'm not sure if you can get around variable-like names then.

I'm +1 on keeping English in the source, for the reason @callahad mentioned.

Would be nice if we could generate the `*.mo` files during build, rather not have them in git.

**Comment by onli** [comment]
> Without that, how else would we flag strings that need updates?

Well, we would not, not in the code. There would be just new text in one language and older text in another if someone updates only the english text. If something really has to be updated now the one that changes the english text could just copy the english phrase over the existing translation. The nice thing about that is that someone fixing a fault in the english text does not have to open the rust code, and a translation interface could still compare english against the other languages (there are some online projects for that, though I'm not certain they have that feature). Our list of texts to translate is small and unlikely to grow much, I think that could be okay for us.

But the drawback is indeed that translations can become stale. Oh, and that all .po/.mo files needs to contain all msgids. If you both still prefer having full english phrases as the msgid, give me a sign and I'll change it.

> > Those *.mo files are binary and maybe should not be in the repo, but then we need to setup Heroku to compile them
>
> Would it make sense to compile them on the fly at server startup? What's a normal workflow there? 

Normal workflow is adding that compile step to the makefile. Would the right place for us be the build.rs? cargo build does execute that? Can external dependencies (`msgfmt`) somewhere be specified?

If that gets complicated, easiest solution could be if I generate a simple Makefile and place it under lang/.

> Maybe we can have the template helper merge in all translations, considering we don't have a lot anyway? Might make things easier, but I'm not sure if you can get around variable-like names then.

I looked a bit at https://github.com/nickel-org/rust-mustache and it seems to be not possible with our current solution. We could switch to https://github.com/sunng87/handlebars-rust. But I can live with the variable approach.

**Comment by skorokithakis** [comment]
I've done extensive localization, and I also agree that English should go in the source. gettext marks translations as fuzzy if the source has been changed, and (I believe) gives you the option to keep the old translation, or show the English version. That's how Django did it, that's how America does it, and it's worked out pretty well so far.

**Comment by onli** [comment]
Okay. I'll change, test and send a PR

**Comment by onli** [comment]
Since the Pr is merged I'll close here.
