### ISSUE TITLE
Gmail with a custom domain

### ISSUE THREAD

**Issue by edas** [portier/portier-broker#140]
Portier doesn't seem to detect Gmail accounts with a custom domain (Google Apps, G Suite). 

I don't know if it's really a goal, nor how the autodetection is going on, but most systems based on openid were correctly identifying my domain and redirected me to the Google login, so it should be feasible.

Context : Fill an email managed by gmail but with a domain different from @gmail.com

Expected : Being redirected to the Google SSO

Actual result : Being redirected to the 'confirm by email' flow

**Comment by onli** [comment]
I did not find this at first neither, but this was discussed in #44 and in the comments of the announcements on Hacker News, https://news.ycombinator.com/item?id=12839055. I think #44 got sidetracked and we should implement G-Suite/Google Apps detection as far as possible. If checking the MX record is not enough to catch all, it might still be better than catching none.

Possible related with https://github.com/portier/portier-broker/pull/97. A check for MX records there could go together with checking the one for  custom Gmail accounts.

It is possible we as a project will need help from someone running such a setup to implement this.

**Comment by callahad** [comment]
I'd lean toward WONTFIX on this; I believe the rationale in #44 is still valid. But it does mean we need to figure out a federated protocol sooner rather than later. I haven't had time to properly look into it yet, but it seems like https://spresso.me/ may be an interesting take on that.

**Comment by callahad** [comment]
Closing as WONTFIX (but wish we could fix -- suggestions welcome!)

Here's an example scenario:

1. I set up a G Suite distribution list for my operations team, `ops@example.com`, and use that to sign up for a server monitoring service.
2. This works with Portier, because distribution lists can receive email.
3. Portier turns on G Suite detection, and forcing `*@example.com` through Google's OpenID Connect flow
4. This doesn't work with Portier, because distribution lists (and account aliases, afaik) can't be used to complete authentication via Google's OpenID Connect endpoint.
5. I'm now locked out of my monitoring account.

Because Google doesn't support Webfinger or any other sort of standard discovery mechanism, from Portier's perspective this failure is indistinguishable from "the user does not have access to that account." Which means our only responsible option is to refuse to authenticate the user.

I believe that failure mode is bad enough to justify skipping on this feature, for now, but if anyone has ideas to mitigate it, please chime in. Perhaps by giving domains the ability to explicitly opt-in to the G Suite workflow?

**Comment by callahad** [comment]
Closing and applying a "Ideas Needed" label
