### ISSUE TITLE
Portier Broker could prompt for login_hint

### ISSUE THREAD

**Issue by colemickens** [portier/portier-broker#166]
The client is currently required to send:
- `login_hint`
- ~~`nonce`~~

As an example, Dex does not send these, so is currently not working with Portier.

~~I don't see that either of those should be explicitly required. It seems that `state` is used for security validation most times anyway, and that `portier-broker` could have another page that prompts the user for entering their email instead of every OIDC client needing to implement a way to get `login_hint` from the user.~~

I think `login_hint` could be omitted and Portier could prompt for it.

**Comment by stephank** [comment]
For `nonce`, it's used to prevent replaying the token, though I'm honestly not sure how one would pull off such a replay attack. But I'm also hesitant to remove it, because it's also required in the OpenID Connect implicit flow we based the protocol on: https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthRequest

But I think we could relax the `login_hint`? I don't think it has any security benefit (on top of `nonce`). We'd have to add a HTML form for it.

**Comment by colemickens** [comment]
Aha, regarding the `nonce`, I don't know how I read so much specs last night and still got that wrong. Thanks.

I'll update the title and edit to remove mention of relaxing the nonce need. I'm working on the `login_hint` form, it was pretty straight-forward.
