### ISSUE TITLE
Support for other response_types?

### ISSUE THREAD

**Issue by colemickens** [portier/portier-broker#168]
Is it intentional that only `implicit` response type is supported?

Would a PR for `code` response type be accepted?

**Comment by stephank** [comment]
We use the `id_token` response type because we only verify identity. We also add some additional fields to the JWT token returned.

If I'm not mistaken, the `code` response type in OAuth2 implies creating a session on the server. The server returns the short-lived `code` to the client via the UA, which the client then uses to get an access token directly from the server. Following all that, we'd have to define how the server provides the data needed, which is normally in the JWT.

So, we use the `id_token` response type with the implicit flow, because it's really simply and meant for our use case. The authorization code flow would triple the amount of state we track, and I haven't yet discovered any benefit.

**Comment by colemickens** [comment]
Thanks for all of that detail @stephank. (Note, while the non-implicit flows do create a "session" with regards to the issued code and exchange for token... it seems that Portier is already keeping some broker-side state/session while the user validates their email, it's a similar flow even. This is assuming I'm understanding things right after poking around for a short while.)

Regardless...

From what I'm reading, when using `response_type=id_token` it is only appropriate to use the implicit flow. Given that, my request seems invalid, so I'm going to close it.

Additionally, it looks easy to support the implicit flow anyway...
