### ISSUE TITLE
Use templates for the email message.

### ISSUE THREAD

**Issue by stephank** [portier/portier-broker#17]
From a TODO in the code: https://github.com/portier/portier-broker/blob/5631a7ed81bff54776669dafd7df3c08a78519ea/src/email.rs#L63

Compile-time or run-time?

Run-time of course means more files (right now just the binary and config), but also more configurability without a rebuild. For run-time, I'm leaning towards [liquid](https://github.com/cobalt-org/liquid-rust).

But compile-time may be good enough for us, considering the primary goal is a central hosted service.

**Comment by djc** [comment]
I think the same approach as is used for `FORWARD_TEMPLATE` is probably good enough. We might want to extract the `replace()` calls in `return_to_relier()` into a more general `template()` function that takes a `Map` for string replacements.

What do you like about liquid? I looked at all the templating options, but I didn't find them all that attractive TBH. Also, since we really only need simple substitution, it feels like overkill.

**Comment by stephank** [comment]
Good point. Not sure why I mixed up compile-time with when the template is executed. We can keep doing the current simple substitution, which is good enough, and load templates at runtime.

I'm personally in favour of loading them at run-time, instead of doing `include_str!`, just because recompiling to change templates feels weird, and especially doesn't make sense for Docker images.

What I have in mind is a toplevel `tmpl` directory (so next to `src`) containing all templates, and I think it's fine just hardcoding relative `tmpl/foobar.html` paths and unwrapping.

I imagine we'll have a bunch of templates down the road: the current forward template, plain text email, HTML email, a form for manually submitting the email code, error pages, etc.

**Comment by djc** [comment]
Alright, that makes sense. So maybe first change the current templates to be used at run-time, then add some new ones? If we need more than just variable substitution, I'd personally lean towards tera, but we can discuss on which of the existing templaters best serve our needs.
