### ISSUE TITLE
Any problem with setting X-Frame-Options to SAMEORIGIN?

### ISSUE THREAD

**Issue by greglearns** [portier/portier-broker#196]
I'd like to make logging on with Portier easier for my Progressive Web Page (PWA) users, and I have a site that doesn't enable people on subdomains to run any code. I was considering forking the repo and changing `hyper::header::X_FRAME_OPTIONS, "DENY"` to SAMEORIGIN, using an iframe in my PWA app for Portier so that the user can start logging in with Portier, but still have access to the current browser page, since in my app the user can keep interacting with the site even if you are not logged in, with only some content/interaction no accessible if you are not logged in. Is this a bad idea?

**Comment by stephank** [comment]
That's a tricky question. I *think* maybe it's safe if there's no untrusted JS on the page?

But I'm also not sure it'll work with GMail, for which we switch to Google login instead of sending a code. I never checked, but wouldn't be surprised if Google also set that header for its login pages. (And maybe there will be more providers in the future.)

I think we only support:
 - Using `state`, for example to remember where the user was, or
 - Using a popup/new tab. The `redirect_uri` could be a page that simply notifies the original tab using JS, so it can update, then closes the login window.

Another thing is: it's possible for a user to follow the email login link on another device.

**Comment by greglearns** [comment]
Good insights. Thank you @stephank
