### ISSUE TITLE
CORS Support

### ISSUE THREAD

**Issue by atbentley** [portier/portier-broker#198]
I'm hosting my own broken and in order to streamline the experience I'd like the make the initial authentication request as an async request in the background, rather than navigating the browser to the auth endpoint.

Since there is already a list of allowed origins, would it make sense to add an option to enable CORS for those origins? If so, which endpoints do we want to enable CORS for, all endpoints or only some?

I am happy to look into this further and see how a PR goes

**Comment by stephank** [comment]
Do you want the request to still return the HTML page, even though you're using it from JS? As it stands, the auth request may immediately redirect the user to GMail or a custom identity provider, which would break CORS, I guess. Though maybe you could do `fetch()` with `redirect: 'manual'` to get the URL in JS and handle that separately.

Or we could maybe turn it into a JSON API for trusted sites, when it sees `Accept: application/json`. For email, it'd say 'post the verification code to this URL', and for GMail or others it'd tell the API the URL to redirect to.

This should definitely be a separate config flag, though. I can see the benefits when both site and broker are run by the same party, but when that is not the case, such an API would leak information about the users email provider. So maybe add a `trusted_origins = [...]`, and optionally allow `trusted_origins = 'allowed_origins'` if the two lists are the same?

**Comment by stephank** [comment]
cc @greglearns, I'm not sure if this interests you too, since you were looking at a different approach for a similar idea in #196. (Feel free to unsub from this issue if not.) 🙂

**Comment by atbentley** [comment]
Ah, I hadn't thought of the gmail side of things since I'm not using that.

My initial though was to change the template from something that looks like html to something that looks like json, but that's more of a hack. Content negotiation and a proper json response seems like a better approach.

Should we break these out as two separate issues? One being CORS and one being content negotiation?

**Comment by stephank** [comment]
That's not necessary, I think. If there's going to be a JSON API for trusted origins, CORS headers should be applied to only that, and only for those trusted origins.

**Comment by greglearns** [comment]
Maybe my use case will help spur ideas for people running their own brokers: @stephank Thank you for pulling me into this related issue! My initial need is that when I want a user to authenticate, I don't want to BLOCK their forward interaction with my website/app until they finish Portier authentication, especially since I've had user experience waiting for 10+ minutes for the authentication email to show up (https://en.wikipedia.org/wiki/Greylisting), or even worse, they end up waiting and then they click to re-authenticate, causing the verification emails and the HTML page where they can enter their authentication code to get out of sync, which causes confusion and failed logins (also, I THINK that if a person logs in multiple times, doesn't the previous validation emails become invalid even for clicking on?).

As a result, I'd like to asynchronously start the login process if needed. I'm still not sure of the best way to do that since it sounds like Portier is mixing "synchronous" (Gmail can instantly return) with "asynchronous" (email can take 10 minutes), which lead me to consider the IFRAME approach, which is not effective for other reasons (gmail rejects it).

On a related issue for people deploying their own Broker (which is required in order to change the default HTML messaging on the "enter your code here" page) who want the benefits of Redis without running Redis, it looks like you @stephank just merged code to use an in-memory store optionally, so one can still include the one-time nonce to avoid replay attacks, correct?

**Comment by stephank** [comment]
@greglearns We don't invalidate links if you retry with the same email. Links do simply expire after 15 minutes, though.

I haven't encountered greylisting myself, that's unfortunate. It sounds like something that heavily depends on the SMTP server used, and maybe DNS settings? For reference, the public broker uses Sendgrid, I manage a private broker for $work that uses Amazon SES, and I also have a bunch of experience using Mailgun in other projects. Those are all safe choices, but I realize choice is sometimes a luxury.

The broker storage option and nonce are unrelated, so yes, you must always include a nonce. The storage option doesn't meaningfully change anything in broker behaviour. Using memory storage is not recommended, though, because the broker will lose signing keys, sessions and cache across restarts. I'd recommend simply using SQLite or Redis.

I can try whip up a quick JSON API on a branch, though I'm still thinking what it'd would look like. Right now, I think it could look like this:

1. JS fetches a nonce from the server.
2. JS sends the `/auth` call to the broker.

If the `/auth` response indicates a verification code was sent, the site should prompt for the code, and when the user enters it:

3. JS sends the `/confirm` call to the broker.
4. JS sends the JWT received to the server.

The `/auth` response may also indicate it wants to redirect the user. In this case, the site should follow that redirect, perhaps in a new tab, and the server will receive the JWT directly when the browser navigates to `redirect_uri`. (How to communicate this back to the original window is up to the site to implement.)

*But the user may also follow the email link*, in which case the server also receives the JWT directly when the browser navigates to `redirect_uri`. (And in this scenario, it may be on another device!)

Alternatively, we can combine 1 & 2 and 3 & 4 by having the *server* call the broker. That'd eliminate CORS handling, and basically mean we just implement JSON responses for `/auth` and `/confirm`.

**Comment by stephank** [comment]
So I've created a [`feat-json`](https://github.com/portier/portier-broker/tree/feat-json) branch and I modified the CI run to upload builds. Here's the one I just ran: https://github.com/portier/portier-broker/actions/runs/64561971

I don't think this has any security implications. All the info now in JSON was already in HTML responses as well, plus I haven't yet opened up any CORS stuff.

Because there's no CORS, you need to talk to your broker from your server right now. (But maybe that's better any way?) You'll need to send `Accept: application/json` to get a JSON response.

For `/auth`, you'll get one of:

```json
{ "result": "verification_code_sent", "session": "..." }
{ "result": "redirect_to_provider", "url": "..." }
```

In the first case, you can POST to `/confirm` with params `session` and `code`. In the second case, you open the url in the browser somehow. In both cases, you must also always handle the user returning via `redirect_uri`.

For `/confirm`, you'll get:

```json
{ "id_token": "...", "state": "..." }
```

This is like `redirect_uri` query params: `id_token` is the JWT, and `state` whatever you passed in to `/auth`.

For any route, errors look like:

```json
{ "error": "...", "error_description": "...", "reference": "..." }
```

This is also like `redirect_uri` query params: `error` is an [OAuth error code](https://tools.ietf.org/html/rfc6749#section-4.1.2.1), `error_description` a human readable string for display.

The `reference` field is new, and can be `null` or a string for display to the user. It's a string in case of internal errors that the broker has logged, so the user can show that reference number to an admin.

Note that I didn't really test this very well. It's just something I quickly hacked together. (But I don't see any security issue, and tests pass, so...) 😀

**Comment by atbentley** [comment]
Thanks for the quick branch. Looks like the linux binary (running inside docker) has some issues?

```
ERROR  [REF:64uemf] could not send mail: description() is deprecated; use Display
```

My dev computer runs macos and the macos binary seems ok. Here are my steps to reproduce it:

First I downloaded the linux binary, and put it into this dockerfile:

```Dockerfile
FROM debian:buster

RUN apt-get update -y
RUN apt-get install -y openssl libssl-dev

COPY portier-broker /bin/portier-broker
COPY lang /portier/lang
COPY res /portier/res
COPY tmpl /portier/tmpl

WORKDIR /portier

ENTRYPOINT ["/bin/portier-broker"]
```

I then used this docker compose file:

```yaml
version: '3'

services:
  portier:
    build:
      context: .
    ports:
      - "3333:3333"
    environment:
      - BROKER_LISTEN_IP=0.0.0.0
      - BROKEN_LISTEN_PORT=3333
      - BROKER_PUBLIC_URL=127.0.0.1:3333
      - BROKER_ALLOWED_ORIGINS=http://127.0.0.1:5100
      - BROKER_MEMORY_STORAGE=true
      - BROKER_FROM_NAME=Portier
      - BROKER_FROM_ADDRESS=<redacted>
      - BROKER_SMTP_SERVER=<redacted>
      - BROKER_SMTP_USERNAME=<redacted>
      - BROKER_SMTP_PASSWORD=<redacted>
```

Brought it up with `docker-compose up`

And then gave it a curl:

```bash
curl -v "http://127.0.0.1:3333/auth" \
  --header "Accept: application/json" \
  --data-urlencode "login_hint=<redacted>" \
  --data-urlencode "scope=openid" \
  --data-urlencode "nonce=628ec5c8003645b2a7fe8633152f8167" \
  --data-urlencode "response_type=id_token" \
  --data-urlencode "response_mode=form_post" \
  --data-urlencode "client_id=http://127.0.0.1:5100" \
  --data-urlencode "redirect_uri=http://127.0.0.1:5100/test"
```

I get the same error if I remove `--header "Accept: application/json"`. If I use the same curl against the macos binary it is fine.

I tried to do a little bit of digging, looks like [you removed `description` from error.rs last year](https://github.com/portier/portier-broker/commit/ac3ef2744a1ffa50789b4ae4fa653d72ff792bed#diff-9a269209bed069ffb36d5565a91c9840L88), maybe this is from a dependency? Or maybe the linux build is somehow pulling old code?

**Comment by stephank** [comment]
@atbentley Yes, that's probably https://github.com/lettre/lettre/issues/401. I ran into this as well. 😕

If it works on Mac but not on Debian, I suspect it's a difference in root certificates or something in TLS. You could try debug with the OpenSSL CLI:

```bash
# With STARTTLS:
docker-compose exec portier \
  openssl s_client -starttls smtp -connect <hostname>:25 -verify_hostname <hostname>
# With opportunistic TLS:
docker-compose exec portier \
  openssl s_client -connect <hostname>:465 -verify_hostname <hostname>
```

And look for: `Verification error: ...`

In my case, I was apparently connecting to the wrong hostname for my mail provider.

If it says `Verification: OK`, then something else is going on. But I'm afraid the only way to get some more info is to place a hack here to debug print the error: https://github.com/portier/portier-broker/blob/935fcce0405fd0e3ac70ee8922c0f62bf0823a75/src/bridges/email.rs#L98

Something like:

```patch
-        .map_err(|e| BrokerError::Internal(format!("could not send mail: {}", e)))?;
+        .map_err(|e| BrokerError::Internal(format!("could not send mail: {:?}", e)))?;
```

**Comment by greglearns** [comment]
Summary: the JSON api's work for `/auth` and `/confirm`, but it appears that something broke when I click on the link in the email.

Context:
Running Portier on PORT 3333, and my app on 1234, sending email to AN_EMAIL_ADDRESS@gmail.com, and using Httpie https://httpie.org/ instead of curl (see command below. Note, httpie is working fine, so it is not the source of any problem)

This works:
```
http -f POST localhost:3333/auth redirect_uri=http://localhost:1234/auth/portier/verify client_id=http://localhost:1234 nonce=123 response_type=id_token scope=openid Accept:application/json login_hint=AN_EMAIL_ADDRESS@gmail.com state=111
```
returning:
```
{
    "result": "verification_code_sent",
    "session": "GGjEv5PdArRvlqzxGncTB0MGoaOcth-tHV9-Ica9i6c"
}
```
and then, this also works:
```
http -f POST localhost:3333/confirm Accept:application/json session="GGjEv5PdArRvlqzxGncTB0MGoaOcth-tHV9-Ica9i6c" code=c7btkeeae1ox
```
returning:
```
{
    "id_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6Ik80MWlvV0taUjR0RllReHlpTXBuTnFBajdtSUw2RmE2R0ZPUkE4S2ZYR00ifQ.eyJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjEyMzQiLCJlbWFpbCI6ImdlZHc2NEBnbWFpbC5jb20iLCJlbWFpbF9vcmlnaW5hbCI6ImdlZHc2NEBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNTg2MTU4Mjk5LCJpYXQiOjE1ODYxNTc2OTksImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzMzMyIsIm5vbmNlIjoiMTIzIiwic3ViIjoiZ2VkdzY0QGdtYWlsLmNvbSJ9.faLRU2vDNJC74P6sOLo9WbzNJez1Dzfzq1ghB9iBzuJ-m962Daj54Gg_5Rfs9NV2oPwrRyCOfPjKNzmZ_vAxeNc_ZIEXo8L3dSe4dIDXuVpg3ckaYJQePCGF4n_Jb36LKfpxvH2ieDYXQCoqeW9HeBALl99oii9miInCv0wPM3AcqggFWZ9s3OAnNdUs8lUveAyfuwLkQrnaZ3mW2UGB-hUP_0gmu7loTa7VLvy7sycUT7z2ZWehr5wgncCNoOQ9UKrDirtEmVOPnBYVPsXRYSy4Mdt2PgA8aHN0LL7HcNEukefgmqWzIAASW5yym73l5kUSw9uiqfHnbYVsSp5c7XTchaPfeTWR2c324ePiP7YIM9HlxWGkJ9M2cBuqahbkQcR3oYg9uO9iIXT4LqUQkfNvK2zdJ2HFPm9rjmVspNbaerOTmYaF-OrNr_AlYlDNYU5-OalLhdT25d5kuowlA-er3hIFr2xvwrdhWlwPhPevpuiThCR8EuI6YBddQBszV4DdKgY6uGaQrdc0uk8_gROFzy8dbaWTYy4u2KBElETBPQCIUWFuf3KMknzI2K3mFoBVfAxCpqFerSjYkcnGPY_rq-JiGQlkQSR36-idvlhwdwmT1-ldmkCj3xjcjxTMtAQ_BInf1C8YUsKhf8Vb-7ATt2MCIzIa_sYZMcZHzd4",
    "state": "111"
}
```

Now, this is the problem:

In  the generated email, the link is:
```
http://localhost:3333/confirm?session=GGjEv5PdArRvlqzxGncTB0MGoaOcth-tHV9-Ica9i6c&code=c7btkeeae1ox
```
But clicking on the link connects to Portier, returns `Error in response: ContentType`. In detail, clicking the link in the email appears to go to Portier, but then when Portier redirects to my app, I think that is where the problem is occurring.  Note: I don't think it is my app, since my app works fine with the https://portier-demo.herokuapp.com/ app.

Not sure if this is the issue: it is possible that the signing keys are off: in the config.toml file, I have 
```
keyfiles = ["/Users/greg/code/private_rsa_key.pem"]
```
which is what I used to create a ".der" public key (my code is months old). So, not sure if Portier changed things that would break the pem/der keys.

**Comment by stephank** [comment]
Your config should continue working, I don't think that's an issue.

Is `Error in response: ContentType` something your application prints? Do you have more info where it's coming from? Also maybe some info about the programming language / env you're using, and if you're using one of the existing Portier client libraries.

Aside from the HTTP responses the browser sees (it doesn't look like a browser error), the only HTTP responses in the `redirect_uri` flow are from fetching `/.well-known/openid-configuration` and `/keys.json`. So I'm wondering if one of those is failing?

(The branch doesn't change the code for those routes. But then again, the branch also passes tests, which include tests for this flow. So this is a bit of a mystery.)

**Comment by greglearns** [comment]
The JSON stuff looks good, but heads up about the non-json / standard approach in a CORS setup. If I have a static UI at https://SITE.com, deploy Portier to https://login.SITE.com, and have an API at https://api.SITE.com, and after I enter the email code to the Portier form and click on submit, then this happens:
1) POST to portier's /confirm -- this is fine
2) GET to forward.js   -- in CORS, because this is a redirect, sets the ORIGIN to "null"
3) POST to the api at /verify -- this fails because `Access-Control-Allow-Origin: null`; unless "null" is added as an allowed origin, which is a security risk (see https://portswigger.net/research/exploiting-cors-misconfigurations-for-bitcoins-and-bounties "The null origin")

Example CORS code below
```
                Cors::new()
                    .allowed_origin("https://login.SITE.com")
                    .allowed_origin("https://www.SITE.com")
                    .allowed_origin("null")
                    .allowed_methods(vec![ "GET", "POST", ])
                    .allowed_headers(vec![ header::AUTHORIZATION, header::ACCEPT, header::CONTENT_TYPE, ])
                    .max_age(10)
                    .supports_credentials()
                    .finish(),
```
Notice the `.allowed_origin("null")` which will make the `forwards.js` succeed. Without that line, it fails because `Access-Control-Allow-Origin: null`.

**Comment by stephank** [comment]
Ah, that's super interesting. Didn't know CORS worked that way, but if so, could CORS ever work for Portier?

I feel like adding CORS support is a bit scary in general. I'd rather you have your own server as a middleman using the new JSON responses. Both `/auth` and `/confirm` already require a call to your own server any way.

I'm going to create a PR for the JSON stuff, along with some small fixes.

**Comment by greglearns** [comment]
To overcome the CORS null issue, Portier would need to not redirect (changing a GET to a POST) before hitting the user's pages (I'm about 85% sure this is correct, so you should verify this).

I still think there is value in Portier as a standalone system. When I was getting started, being able to point to https://portier-demo.herokuapp.com/ to use as my app's authentication method was helpful. Solving the CORS issue could have real value.

If you self host Portier and run it as a non-web-facing service and use JSON for `/auth` and `/confirm` then does one need to have a JWT since it will be possible to trust the `/auth` and `/confirm` responses?

**Comment by stephank** [comment]
Oh, merging the PR closed this, but feel free to reopen if you think CORS is still an issue.

The idea is that we're deploying this to the public broker too, and it will also support JSON responses. So self-hosting is optional, but the plan currently is to update the public broker May 11th.

I believe the JWT is still required to handle users landing on `redirect_uri`? I don't see a way to do that without a JWT. I guess, you could eliminate `redirect_uri` by modifying the broker to remove GMail auth (and any other OIDC auth), so email-only, then have it create email links that point directly to some new route in your own application.

I think it's a cool idea, and but also wonder if it wouldn't complicate portier-broker quite a bit with toggles that are hard to explain.

But on CORS, I feel like maybe I'm missing something you're trying to explain? The way I see it, `/auth` and `/confirm` both require work on your server and the broker. You can implement the calls to the broker as part of the work you do on your server, so your client-side can do `/auth` and `/confirm` with 1 request each. If we added CORS to the broker, that would allow implementing the broker calls client-side, but you still have to do the work on your own server, so `/auth` and `/confirm` become 2 requests each for the client.

**Comment by stephank** [comment]
I created 0.3.1, and deployed it to the staging broker at `https://broker.staging.portier.io`. The JSON API is now available there. The plan is to have it on production May 11th.
