### ISSUE TITLE
Matrix room

### ISSUE THREAD

**Issue by colemickens** [portier/portier-broker#216]
Shall we start a Martix room to be able to chat about Portier?

**Comment by colemickens** [comment]
(I checked on Mozilla's instance and didn't see one)

**Comment by stephank** [comment]
There's no official connection with Mozilla, except for some contributors who sometimes used company time, but have since become inactive.

We currently have a Gitter room, as listed on the main website: https://gitter.im/portier/Lobby

But, IMHO, Gitter may not be the best option anymore. It seems to have stagnated completely since the GitLab acquisition. I only ever seem to find @onli in our chat, so pinging to get his input. 🙃

Personally, I have 0 permanent presence in OSS chat channels. I visit the Portier chat every couple of days to check, and other channels whenever I'm interested in something specific. So that makes the choice of which chat service to use a little difficult for me.

I'm also concerned switching chat channels too often won't help people to find us, but I'm on the fence, because I wonder how many people actually read our Gitter channel right now.

My 2 cents:

- Zulip: I'm a little hyped for this currently, because it is has great threading, but haven't used it seriously, nor tried mobile apps. No federation. No public chat log.
- Matrix: Only played around a little with app.element.io. Open standard / federation / many apps available are selling points. No public chat log?
- Gitter: Still works fine, but iOS app stinks. Does have a public chat log, though.
- IRC: No history at all, and don't believe this is user-friendly anymore.

**Comment by onli** [comment]
No strong opinion here.

My take: We had a little bit of activity on gitter, didn't we? If you are convinced opening a room somewhere else would make it easier for others, sure, go ahead (and I'll join). But I think given how easy it is to log in to gitter I doubt a different service would be useful.

**Comment by colemickens** [comment]
Matrix: the room will have public scrollback by nature of being a public room. (Also, Matrix plans to add threaded conversations in the future.)

Also, we can bridge (two-way) the Gitter room into the Matrix room, so no need to worry about fragmenting conversations.

I have looked at Matrix a few times over the years. It has, over the past 7 months, very much tripped my "this is not just good, but going to take off" meter. Still a few growing pains here and there but nothing that would affect a small room.

I went ahead and made [#portier:matrix.org](https://matrix.to/#/#portier:martix.org) but I'm happy to handover/co-admin with whoever is maybe more suited. I assume someone would need to be an admin on the org/repo/gitter-thing in order to complete the bridge process (if it's worth doing).

**Comment by stephank** [comment]
Maybe Gitter has fixed this for us? 😀
https://matrix.org/blog/2020/12/07/gitter-now-speaks-matrix

**Comment by onli** [comment]
Definitely seems like it :)

**Comment by colemickens** [comment]
We'll see... I pinged Matrix HQ... 
![screenshot-1607463890](https://user-images.githubusercontent.com/327028/101545100-9801e400-395b-11eb-82da-76c338c207bd.png)

**Comment by colemickens** [comment]
Works for me. Cheers, closing this out.
![screenshot-1607464367](https://user-images.githubusercontent.com/327028/101545815-ab617f00-395c-11eb-824e-36f3fbc301f3.png)
