### ISSUE TITLE
Detect G Suite domains

### ISSUE THREAD

**Issue by stephank** [portier/portier-broker#44]
Currently, it's possible to get the oidc flow for a G Suite domain by simply copying the provider section for gmail.com for each domain you want. It'd be neat if we could detect domains that run mail through G Suite.

Is checking MX records enough? This was on the backlog for Persona, so I'm not sure what their findings and experiences are, but that would be valuable to look into.

**Comment by buro9** [comment]
Checking MX is not enough. It's only good for simple G Suite customers, but it's possible (and many companies do) to use different MX records and just eventually route to Gmail. i.e. you continue to publish your own MX, you run Postini (now dead) or SpamHero or whatever on it... applying cheaper polices for retention, etc... and then eventually route through to Google.

I think the Google sign-in is simply if we just offer a button.

Seriously.

I've had to integrate auth0 on one of my sites as the customer of that site needed SAP SSO integration and auth0 already provided it. But in needing to test auth0 I have tried their passwordless thing, and this is the outcome (conversation with @callahad ):

<buro9> David one of the things I've noticed from that, is Google Auth is loved. 48% of my signins on the 2 large sites I have switched (the client who wanted SAP, and one of my own as I needed to test stuff)... is all Google Auth
13:39:36 and the other thing I noticed... of the Google Auth signins, only ~65% is for the gmail/googlemail domain
13:39:52 C<callahad> Really, that low?
13:40:01 B<buro9> that is... a huge number of people, when given the obvious option, choose to use the Google flow for their personal/work domain
13:40:52 so when it comes to UI/UX, I'm back to offering an obvious "Sign-in with Google" button above a "Or enter your email" field
13:40:58 C<callahad> Well, damn. That means we may want to try to be a bit more aggressive in detecting Google Apps domains.
13:41:27 What's the audience for this site? Technical people at all? business folks?
13:41:55 B<buro9> I only tested 3 options with auth0 on my own site, for the purpose of seeing how Portier would work out... Google Auth, Windows Live, and code via email
13:42:25 Google Auth wins at 48%, then code via email at 31% and finally Windows Live

You only get 3 options for free with auth0 otherwise I would have tested more.

But the outcome:
* 48% of users opt to sign-in with Google if the option is visible.
* Of those, only ~65% were on gmail.com or googlemail.com (35% didn't)
* Some ~17% of the total users (5,000+ seen during the test) signed in with Google using a non-Google domain

That's so significant I think we should not be so holy about the single field login form and consider just adding a button to trigger the Google flow.

**Comment by callahad** [comment]
There are a *lot* of corner cases here, to the point where we weren't comfortable rolling it out. From memory, there were two main issues:

**It's virtually impossible to be confident in coverage:**

- You can have a G Suite accounts without them being smtp-deliverable.
- You can have smtp-deliverable G Suite accounts without G Suite MX records.
- As far as I know, there's no API (webfinger, etc.) that allows proper discovery of domains or user support for G Suite.

**Gmail's address normalization rules don't necessarily apply:**

- G Suite addresses aren't dot-insensitive.
- G Suite accounts can have aliases, which aren't necessarily exposed over federated endpoints.
- G Suite domains can have smtp-deliverable distribution lists that aren't exposed over federated endpoints.

**Comment by callahad** [comment]
That might not be the right grouping of the bullets, but the core idea is that if we rolled it out, it'd have to have completely different normalization paths than Gmail accounts, and we'd likely lock people out of websites if they were using an alias or a distribution list, which is especially common in small startups -- e.g., registering for services using a shared `founders@` account.

I think a better path forward is defining our federated protocol and making an absolutely trivial adapter between that and G Suite for domains that want to *opt in* to support, in full knowledge of the associated risks.

Or just have the domains implement webfinger pointing to Google's discovery doc? Or flag it some other way -- a DNS record or well-known file? But I don't want to give Google *that much* special treatment.

**Comment by stephank** [comment]
Considering all the corner cases, an opt-in seems reasonable.

@buro9 Considering the login form is on the RP, adding a Google signin button would be tricky in the current flow. We introduce an extra step, and the user probably entered their email address for nothing.

**Comment by onli** [comment]
And it would completely break the layout of sites tailored to persona. Already the current form does not always work well for existing layouts, but multiple buttons will break everything completely.

**Comment by callahad** [comment]
Closing as WONTFIX for now. I'd *really* like to keep the Broker as close to a no-ui, email-only, backend service as possible.

To @buro9's stats (wow!), I think there's absolutely room for a separate project under the Portier umbrella that focuses on the in-page UI. That could be used to unify Google Sign-in, the generic Portier broker, etc. It'd probably need *some* support from from the broker, but hopefully we can avoid completely hosting a multi-button UI in the broker ;)
