### ISSUE TITLE
Generate ephemeral keys when none are provided

### ISSUE THREAD

**Issue by callahad** [portier/portier-broker#60]
For local testing, it'd be great if the broker could just generate a temporary key when none are provided.

**Comment by stephank** [comment]
I was able to build a crude implementation of automatic key rotation, which will also solve this, but it has some downsides:
 - Storage is currently on the filesystem, so this won't work on Heroku, and maybe it's confusing to have state in both Redis and on the filesystem.
 - `ring` can't generate RSA, so the implementation relies on a configurable external command to generate RSA keys. It can be as simple as `openssl genrsa 2048`, but I'm not sure what to do with Windows.
 - I need to clean up error handling in the code. This is my current priority, because I feel it's the only absolute blocker before I can create a PR.
