### ISSUE TITLE
Refactor to provider selection to be more modular

### ISSUE THREAD

**Issue by callahad** [portier/portier-broker#66]
Our level of abstraction doesn't feel right yet. Our [current code](https://github.com/portier/portier-broker/blob/a88f503702e085c868d5aaaa13598ae1f6ba3988/src/lib.rs#L318-L335) basically functions as:
1. If `email.domain` in `providers`:
   1. Get a redirect URL from the openid module
   2. Redirect the user
2. Else:
   1. Get a session ID from the email module
   2. Display the confirm email template to the user

I don't think this is the best solution in a few areas:
- It only switches on email domain. As per #44, we might want to switch on other attributes in the future.
- If two domains are serviced by the same provider, as is the case with `gmail.com` and `googlemail.com` we have to duplicate that in the configuration.
- General OIDC and Gmail-specific rules are commingled in `src/oidc.rs`
- This design presumes that all providers are OIDC providers.
- The returned values aren't unified: you get either a URL or a session ID.
- The redirect logic is split between the individual module and `src/lib.rs`.

I'm not sure how to best address this, but I think the answer might be along the lines of:
- All providers adhere to a common interface or implement a common trait
- Providers completely handle incoming requests and return a ready-to-use `iron::Response`
- Split the generic OIDC provider and the Gmail provider into separate modules. The Gmail one can, of course, rely on facilities offered by the generic one.
- Providers can return whether or not they can handle an address, either through a function returning `bool`, or by returning an `Option<Iron::Response>`.
- We keep a prioritized list of providers, and just iterate over it, trying each one until one succeeds.

**Comment by stephank** [comment]
To be honest, this sounds a bit like over engineering the problem. There's no abstraction there right now, and maybe that's fine for what we're doing. We haven't even hashed out the details of native discovery yet.

**Comment by callahad** [comment]
Definitely a post-MVP thing :)

**Comment by stephank** [comment]
I'm going to close this, because I believe this is as good as it gets for now.

 - We now switch on Webfinger link relation. (For example, the Webfinger result may indicate a Portier IdP or Google through `rel`, which we simply match on.)
 - Bridges now simply return a HTTP response, making the interface more consistent. There's not common interface for calling bridges, but that doesn't impede anything for now.
 - Any (optional) configuration is now just Webfinger overrides.
 - Google (and its multiple domains) will likely keep being a special case. We may add special cases for other providers too. That's fine, I think. Even the OIDC client code shared between Portier IdPs and Google is structured well enough IMHO.
 - Email is always our fallback, and our only fallback. I think its fine to limit our scope to this.
