### ISSUE TITLE
Rate-limit login attempts

### ISSUE THREAD

**Issue by callahad** [portier/portier-broker#70]
Dovetails with #69 -- how often should we allow a single email address + rp combo to request auth codes?

**Comment by stephank** [comment]
So, I think we should:

 - Rate limit the number of sessions created per email.
 - Rate limit the number of code guesses per email (spanning all sessions).

On top of that:

 - Hard limit the maximum code guesses per session, after which we destroy the session.

And also:

 - NOT rate limit on IP. We should always be behind a proxy, which can do that better.

Does that sound right?

Some rate limiting implementation options:

 - Simple `INCR, EXPIRE, GET`. The nice thing here is that an attacker that proceeds past the limit will only extend his ban, without any extra actions going through. Downside is, the expiry should probably be short to not annoy regular users who trigger it by accident.

 - Sliding window using sorted sets, as per https://engineering.classdojo.com/blog/2015/02/06/rolling-rate-limiter/. This stores each action time as the score element of a sorted set, trims the set, then counts the elements. The implementation there may have a flaw of allowing an attacker to fill up memory by infinitely expanding the set. While this can be fixed by trimming by rank instead of score, it may still be troublesome if the maximum count is large.

 - Sliding window using hashes, as per https://gist.github.com/chriso/54dd46b03155fcf555adccea822193da. This splits up the window in buckets, where each hash key is a bucket with a count. The timespan of a single bucket determines granularity, but that means it'll also work well with long time windows.

Something to consider is to add several overlapping limits to a single type of action, e.g.: limit sessions per email to 3 times per 10 seconds, and 1000 per day.

I'm leaning towards the last implementation option, because it seems to handle all sizes of time windows well.

Thoughts and other options?

**Comment by onli** [comment]
> NOT rate limit on IP. We should always be behind a proxy, which can do that better.

We can't guarantee that for every broker out there. If we see an easy way to add IP rate limiting on our side we should include it, especially if it is crucial for our security model. 

http://redis.io/commands/incr mentions rate limiting as an example for the incr command. I think that is what you mean with your first listed implementation option? It should be easy enough to adapt the code there to work with the email address instead of the IP. In this context, IP limiting might be worthwhile to implement directly as well (not as part of this rate limiting, but as an outer rate limit) to prevent the DOS-attack against one email address.

**Comment by callahad** [comment]
> Downside is, the expiry should probably be short to not annoy regular users who trigger it by accident.

Or make it possible to trivial for an adversary to DDoS someone :)

Let's start with the simplest thing for 1.0 and limit the frequency with which any given email address can pass through our system.
