### ISSUE TITLE
Create privacy policy / terms of service

### ISSUE THREAD

**Issue by callahad** [portier/portier-broker#79]
We should have a proper PP / ToS, and add them to the Google API consent screen.

**Comment by onli** [comment]
The problem here is that we are no legal entity, no organization. Accordingly we have no country, meaning it is absolutely unclear with which legal system and standard in mind such a policy should be created. What does proper mean then?

I think we can still fill those documents, but not with legal speak. In the PP, let us describe in simple terms which data we are collecting in the current broker. and how long what is stored. If wanted, I can set up a draft (but of course one of you native speakers will have to check it closely).

I would not know what to write in the ToS though. Don't make a DOS against us? Seems unnecessary to me.

**Comment by callahad** [comment]
See: https://github.com/portier/portier.github.io/pull/27

**Comment by callahad** [comment]
Done. Google API Gateway consent screen updated with the new ToS/PP URL
